apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zapisnikar
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: zapisnikar
    newName: rg.fr-par.scw.cloud/djnd/zapisnikar
    newTag: 'a0a7d9c03d6a5935453c51cf094e12ba9cbce785'
