apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zapisnikar
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: zapisnikar
    newName: rg.fr-par.scw.cloud/djnd/zapisnikar
    newTag: 'afe0cd02925d2ee84a1eb3fde4bc2d525173d10e'
