services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: zapisniki
      POSTGRES_USER: zapisniki
      POSTGRES_PASSWORD: zapisniki
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=zapisniki.settings
      - TIPKO_API_ENDPOINT=https://tipko.si
      - TIPKO_API_USERNAME=username
      - TIPKO_API_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=key
      - AWS_SECRET_ACCESS_KEY=key
      - AWS_ACCESS_KEY_ID=id
      - ENABLE_S3=
      - AWS_STORAGE_BUCKET_NAME=zapisnikar
      - AWS_LOCATION=media
      - DATABASE_HOST=db
      - DATABASE_NAME=zapisniki
      - DATABASE_USER=zapisniki
      - DATABASE_PASSWORD=zapisniki

    depends_on:
      - redis

  huey:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    command: ["python", "manage.py", "run_huey"]
    environment:
      - DJANGO_SETTINGS_MODULE=zapisniki.settings
      - TIPKO_API_ENDPOINT=https://tipko.si
      - TIPKO_API_USERNAME=username
      - TIPKO_API_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=key
      - AWS_SECRET_ACCESS_KEY=key
      - AWS_ACCESS_KEY_ID=id
      - ENABLE_S3=
      - AWS_STORAGE_BUCKET_NAME=zapisnikar
      - AWS_LOCATION=media
      - DATABASE_HOST=db
      - DATABASE_NAME=zapisniki
      - DATABASE_USER=zapisniki
      - DATABASE_PASSWORD=zapisniki
    depends_on:
      - redis

  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/usr/share/nginx/html/media
      - ./static:/usr/share/nginx/html/static
      - ./theme/static:/usr/share/nginx/html/static
    depends_on:
      - django
    ports:
      - 8001:80

volumes:
  redis_data:
  pgdata:
