# Generated by Django 5.2.7 on 2025-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Minutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(verbose_name="Title of the transcript")),
                (
                    "sound_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Sound file of the thing.",
                    ),
                ),
                (
                    "example_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Example minutes.",
                    ),
                ),
                (
                    "transcript_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Transcript file.",
                    ),
                ),
                (
                    "llm_minutes_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Minutes generated by the LLM as a file.",
                    ),
                ),
                (
                    "transcribed_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="The actual transcript."
                    ),
                ),
                (
                    "example_minutes",
                    models.TextField(
                        blank=True,
                        default="\nEn\ndva\ntri\nštir\npet\nšest\n...\n",
                        null=True,
                        verbose_name="How the minutes should look like.",
                    ),
                ),
                (
                    "generated_minutes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Minutes generated by the LLM",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default="You have access to the meeting transcript and an example of what a meeting record looks like. Your task is to create a structured meeting record based on the transcript.",
                        null=True,
                        verbose_name="The prompt that was used to generate minutes",
                    ),
                ),
                (
                    "tipko_task_id",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="The Tipko task ID for transcription.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
