# Generated by Django 5.2.7 on 2025-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlaminutes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="minutes",
            name="error_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Error message, if any."
            ),
        ),
        migrations.AddField(
            model_name="minutes",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_TRANSCRIPTION", "Waiting for transcription."),
                    ("WAITING_MINUTES", "Waiting on generated minutes."),
                    ("COMPLETED", "Completed."),
                    ("ERROR", "Error during processing."),
                ],
                default="WAITING_TRANSCRIPTION",
                max_length=50,
                verbose_name="Status of the minutes",
            ),
        ),
    ]
