from django.conf import settings
from django.db import models
from django.utils.translation import gettext as _


# behaviours
class Timestampable(models.Model):
    """
    An abstract base class model that provides self-updating
    `created_at` and `modified_at` fields.
    """

    created_at: models.DateTimeField = models.DateTimeField(
        auto_now_add=True, db_index=True
    )
    updated_at: models.DateTimeField = models.DateTimeField(
        auto_now=True, db_index=True
    )

    class Meta:
        abstract = True


# Create your models here.
class Minutes(Timestampable):
    title: models.CharField = models.CharField(
        _("Title of the transcript"),
        blank=False,
        null=False,
    )  # no need for max_length=150 since we're using sqlite or postgresql
    sound_file: models.FileField = models.FileField(
        _("Sound file of the thing."),
        # upload_to="sound_files/",
        blank=True,
        null=True,
    )
    example_file: models.FileField = models.FileField(
        _("Example minutes."),
        # upload_to="example_files/",
        blank=True,
        null=True,
    )
    transcript_file: models.FileField = models.FileField(
        _("Transcript file."),
        # upload_to="transcript_files/",
        blank=True,
        null=True,
    )
    llm_minutes_file: models.FileField = models.FileField(
        _("Minutes generated by the LLM as a file."),
        # upload_to="minutes_files/",
        blank=True,
        null=True,
    )
    transcribed_text: models.TextField = models.TextField(
        _("The actual transcript."),
        blank=True,
        null=True,
    )
    example_minutes: models.TextField = models.TextField(
        _("How the minutes should look like."),
        blank=True,
        null=True,
        default=settings.DEFAULT_EXAMPLE_MINUTES,
    )
    generated_minutes: models.TextField = models.TextField(
        _("Minutes generated by the LLM"),
        blank=True,
        null=True,
    )
    prompt: models.TextField = models.TextField(
        _("The prompt that was used to generate minutes"),
        blank=True,
        null=True,
        default=settings.GEMINI_PROMPT_TEMPLATE,
    )
    tipko_task_id: models.CharField = models.CharField(
        _("The Tipko task ID for transcription."),
        max_length=150,
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.title} / {self.created_at} / {self.status}"

    @property
    def status(self):
        # TODO this is quite a wonky heuristic
        if self.sound_file is None:
            return "Everything missing, this shouldn't exist."
        if self.transcribed_text is None:
            return "Waiting for transcription."
        if self.generated_minutes is None:
            return "Waiting on generated minutes."
        else:
            return "Completed."

    @property
    def hydrated_prompt(self):
        return "\n---\n".join(
            (
                self.prompt,
                self.transcribed_text,
                self.example_minutes,
            )
        )
